import os, fnmatch

from SConsCommon import *

Import('global_env')

env = global_env.Clone()

sources = []
globFiles(env, '.', '*.cpp', sources)

program = env.Program('deremotelauncher-linux', sources)

runtimeLibs = []
for l in global_env['RUNTIME_LIB_FOX']:
	env.Depends(program, env.InstallAs(l.name, l))

env.Alias('deremotelauncher-linux', program)
