name: Build Linux

on:
  workflow_call:
    inputs:
      releaseVersion:
        required: true
        type: string
      artifactArchive:
        required: true
        type: string

jobs:
  build_linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install required packages
        run: |
          sudo apt -y install build-essential scons libxft-dev libgl-dev
      
      - name: Init custom.py
        run: |
          cp ${{ github.workspace }}/.github/workflows/custom_linux.py custom.py
      
      - name: Download DENetwork SDK
        run: |
          wget https://github.com/LordOfDragons/denetwork/releases/download/nightly/denetworkcpp-unix-x64-nightly.zip
          unzip denetworkcpp-unix-x64-nightly.zip
          
      - name: Build
        run: |
          scons -j 14 \
            version=${{ inputs.releaseVersion }} \
            denetwork_includes="`realpath denetworkcpp-unix-x64-nightly/include`" \
            denetwork_libraries="`realpath denetworkcpp-unix-x64-nightly/lib`" \
            build archive
      
      - name: Move Artifacts
        run: |
          mkdir artifacts
          cp -a shared/build/deremotelauncher-unix-x64-${{ inputs.releaseVersion }}.tar.bz2 artifacts
          cp -a launcher/desktop/build/deremotelauncherdesktop-unix-x64-${{ inputs.releaseVersion }}.tar.bz2 artifacts
        
      - name: Store Archives
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactArchive }}
          path: |
            artifacts/deremotelauncher-unix-x64-${{ inputs.releaseVersion }}.tar.bz2
            artifacts/deremotelauncherdesktop-unix-x64-${{ inputs.releaseVersion }}.tar.bz2
          if-no-files-found: error
